//
//  ItemsRepository.swift
//  TableInteraction
//
//  Created by anton on 13.12.2019.
//  Copyright © 2019 none. All rights reserved.
//

import Foundation

final class ItemsRepository {

    func items(forOffset offset: Int, count: Int) -> [Item] {
        guard let range = range(forOffset: offset, count: count) else { return [] }
        Thread.sleep(forTimeInterval: .random(in: delayRange))
        return Array(items[range])
    }

    func detail(forItemId id: String) -> String? {
        Thread.sleep(forTimeInterval: .random(in: delayRange) * 2)
        return details[id]
    }

    private let delayRange: ClosedRange<TimeInterval> = (0...10)
    private let items: [Item] = [
        .init(id: "1", title: "title for 1"),
        .init(id: "2", title: "title for 2"),
        .init(id: "3", title: "title for 3"),
        .init(id: "4", title: "title for 4"),
        .init(id: "5", title: "title for 5"),
        .init(id: "6", title: "title for 6"),
        .init(id: "7", title: "title for 7"),
        .init(id: "8", title: "title for 8"),
        .init(id: "9", title: "title for 9"),
        .init(id: "10", title: "title for 10"),
        .init(id: "11", title: "title for 11"),
        .init(id: "12", title: "title for 12"),
        .init(id: "13", title: "title for 13"),
        .init(id: "14", title: "title for 14"),
        .init(id: "15", title: "title for 15"),
        .init(id: "16", title: "title for 16"),
        .init(id: "17", title: "title for 17"),
        .init(id: "18", title: "title for 18"),
        .init(id: "19", title: "title for 19"),
        .init(id: "20", title: "title for 20"),
        .init(id: "21", title: "title for 21"),
        .init(id: "22", title: "title for 22"),
        .init(id: "23", title: "title for 23"),
        .init(id: "24", title: "title for 24"),
        .init(id: "25", title: "title for 25"),
        .init(id: "26", title: "title for 26"),
        .init(id: "27", title: "title for 27"),
        .init(id: "28", title: "title for 28"),
        .init(id: "29", title: "title for 29"),
        .init(id: "30", title: "title for 30"),
        .init(id: "31", title: "title for 31"),
        .init(id: "32", title: "title for 32"),
        .init(id: "33", title: "title for 33"),
        .init(id: "34", title: "title for 34"),
        .init(id: "35", title: "title for 35"),
        .init(id: "36", title: "title for 36"),
        .init(id: "37", title: "title for 37"),
        .init(id: "38", title: "title for 38"),
        .init(id: "39", title: "title for 39"),
        .init(id: "40", title: "title for 40"),
        .init(id: "41", title: "title for 41"),
        .init(id: "42", title: "title for 42"),
        .init(id: "43", title: "title for 43"),
        .init(id: "44", title: "title for 44"),
        .init(id: "45", title: "title for 45"),
        .init(id: "46", title: "title for 46"),
        .init(id: "47", title: "title for 47"),
        .init(id: "48", title: "title for 48"),
        .init(id: "49", title: "title for 49"),
        .init(id: "50", title: "title for 50"),
        .init(id: "51", title: "title for 51"),
        .init(id: "52", title: "title for 52"),
        .init(id: "53", title: "title for 53"),
        .init(id: "54", title: "title for 54"),
        .init(id: "55", title: "title for 55"),
        .init(id: "56", title: "title for 56"),
        .init(id: "57", title: "title for 57"),
        .init(id: "58", title: "title for 58"),
        .init(id: "59", title: "title for 59"),
        .init(id: "60", title: "title for 60"),
        .init(id: "61", title: "title for 61"),
        .init(id: "62", title: "title for 62"),
        .init(id: "63", title: "title for 63"),
        .init(id: "64", title: "title for 64"),
        .init(id: "65", title: "title for 65"),
        .init(id: "66", title: "title for 66"),
        .init(id: "67", title: "title for 67"),
        .init(id: "68", title: "title for 68"),
        .init(id: "69", title: "title for 69"),
        .init(id: "70", title: "title for 70"),
        .init(id: "71", title: "title for 71"),
        .init(id: "72", title: "title for 72"),
        .init(id: "73", title: "title for 73"),
        .init(id: "74", title: "title for 74"),
        .init(id: "75", title: "title for 75"),
        .init(id: "76", title: "title for 76"),
        .init(id: "77", title: "title for 77"),
        .init(id: "78", title: "title for 78"),
        .init(id: "79", title: "title for 79"),
        .init(id: "80", title: "title for 80"),
        .init(id: "81", title: "title for 81"),
        .init(id: "82", title: "title for 82"),
        .init(id: "83", title: "title for 83"),
        .init(id: "84", title: "title for 84"),
        .init(id: "85", title: "title for 85"),
        .init(id: "86", title: "title for 86"),
        .init(id: "87", title: "title for 87"),
        .init(id: "88", title: "title for 88"),
        .init(id: "89", title: "title for 89"),
        .init(id: "90", title: "title for 90"),
        .init(id: "91", title: "title for 91"),
        .init(id: "92", title: "title for 92"),
        .init(id: "93", title: "title for 93"),
        .init(id: "94", title: "title for 94"),
        .init(id: "95", title: "title for 95"),
        .init(id: "96", title: "title for 96"),
        .init(id: "97", title: "title for 97"),
        .init(id: "98", title: "title for 98"),
        .init(id: "99", title: "title for 99"),
        .init(id: "100", title: "title for 100")
    ]
    private let details: [String: String] = [
        "1": "detail for 1",
        "2": "detail for 2",
        "3": "detail for 3",
        "4": "detail for 4",
        "5": "detail for 5",
        "6": "detail for 6",
        "7": "detail for 7",
        "8": "detail for 8",
        "9": "detail for 9",
        "10": "detail for 10",
        "11": "detail for 11",
        "12": "detail for 12",
        "13": "detail for 13",
        "14": "detail for 14",
        "15": "detail for 15",
        "16": "detail for 16",
        "17": "detail for 17",
        "18": "detail for 18",
        "19": "detail for 19",
        "20": "detail for 20",
        "21": "detail for 21",
        "22": "detail for 22",
        "23": "detail for 23",
        "24": "detail for 24",
        "25": "detail for 25",
        "26": "detail for 26",
        "27": "detail for 27",
        "28": "detail for 28",
        "29": "detail for 29",
        "30": "detail for 30",
        "31": "detail for 31",
        "32": "detail for 32",
        "33": "detail for 33",
        "34": "detail for 34",
        "35": "detail for 35",
        "36": "detail for 36",
        "37": "detail for 37",
        "38": "detail for 38",
        "39": "detail for 39",
        "40": "detail for 40",
        "41": "detail for 41",
        "42": "detail for 42",
        "43": "detail for 43",
        "44": "detail for 44",
        "45": "detail for 45",
        "46": "detail for 46",
        "47": "detail for 47",
        "48": "detail for 48",
        "49": "detail for 49",
        "50": "detail for 50",
        "51": "detail for 51",
        "52": "detail for 52",
        "53": "detail for 53",
        "54": "detail for 54",
        "55": "detail for 55",
        "56": "detail for 56",
        "57": "detail for 57",
        "58": "detail for 58",
        "59": "detail for 59",
        "60": "detail for 60",
        "61": "detail for 61",
        "62": "detail for 62",
        "63": "detail for 63",
        "64": "detail for 64",
        "65": "detail for 65",
        "66": "detail for 66",
        "67": "detail for 67",
        "68": "detail for 68",
        "69": "detail for 69",
        "70": "detail for 70",
        "71": "detail for 71",
        "72": "detail for 72",
        "73": "detail for 73",
        "74": "detail for 74",
        "75": "detail for 75",
        "76": "detail for 76",
        "77": "detail for 77",
        "78": "detail for 78",
        "79": "detail for 79",
        "80": "detail for 80",
        "81": "detail for 81",
        "82": "detail for 82",
        "83": "detail for 83",
        "84": "detail for 84",
        "85": "detail for 85",
        "86": "detail for 86",
        "87": "detail for 87",
        "88": "detail for 88",
        "89": "detail for 89",
        "90": "detail for 90",
        "91": "detail for 91",
        "92": "detail for 92",
        "93": "detail for 93",
        "94": "detail for 94",
        "95": "detail for 95",
        "96": "detail for 96",
        "97": "detail for 97",
        "98": "detail for 98",
        "99": "detail for 99",
        "100": "detail for 100"
    ]

    private func range(forOffset offset: Int, count: Int) -> Range<Int>? {
        let from = offset
        let to = offset + count
        guard items.indices.contains(from) else { return nil }
        guard to > from else { return nil }
        guard to <= items.endIndex else { return from..<items.endIndex }
        return from..<to
    }
}
